version: "3"
services:
  mysql:
    image: mysql:5.7.23
    container_name: "compose-mysql"
    ports:
    - "3306:3306"
    expose:
    - "3306"
    volumes:
    - /data/mysql/db:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=firely0506
  mongodb:
    image: mongo:4.1.3
    command: [--auth]
    ports:
    - "27017:27017"
    expose:
    - 27017
    volumes:
    - /data/mongo/db:/data/db
    container_name: "compose-mongo"

  golang:
    image: golang:1.11.0
    container_name: "compose-golang"