version: "3"
services:
  mysql:
    image: mysql:5.7.23
    container_name: "compose-mysql"
    ports:
    - "3306:3306"
    expose:
    - "3306"
    volumes:
    - /var/mysql/db:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=firely0506